[package]
name = "revamp-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.revamp-sc]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
